name: "Auto-update"
on:
  schedule:
    - cron:  '0 0 * * *'
jobs:
  check-and-push-updates:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - run: nix-shell --run "niv update"
    - run: nix-shell --run ./generate.sh
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic updates
